### ISSUE TITLE
Shaders look weird and dont work proprely on my RDNA amd card

### ISSUE THREAD

**Issue by Gromatou** [BalintCsala/VanillaPuddingTart#26] opened 2023-04-19 21:18 UTC
hey ! the shader dont want to work normaly on my old amd setup : rx 570 and ryzen 5 3600xt
here some logs ands screenshots. i've made a lot of try on a lot of versions without any succes

![2023-04-19_23 03 20](https://user-images.githubusercontent.com/117398283/233202377-ec24b1a0-4c35-41a5-947b-3ace7eabddca.png)
![2023-04-19_23 03 22](https://user-images.githubusercontent.com/117398283/233202382-d9927d31-1491-461f-9083-b96f4207a105.png)
[latest.log](https://github.com/BalintCsala/VanillaPuddingTart/files/11277674/latest.log)

![2023-04-19_23 03 15](https://user-images.githubusercontent.com/117398283/233202384-74565ac7-b0be-4a20-8bef-b24a671dae33.png)

**Comment by Gromatou** [comment] 2023-04-19 21:20
![image](https://user-images.githubusercontent.com/117398283/233202745-0db7132f-c08e-4cd7-83f4-7eca1ceaba0d.png)
without vanilla pbr (same)

**Comment by BalintCsala** [comment] 2023-04-19 22:24
Duplicate of https://github.com/BalintCsala/VanillaPuddingTart/issues/22

**Closed as completed by BalintCsala** 2023-04-19 22:24 UTC
Labels: duplicate
