### ISSUE TITLE
Short but descriptive description of the issue, e.g. Shader fails to load

### ISSUE THREAD

**Issue by CrabbyDisk** [BalintCsala/VanillaPuddingTart#30] opened 2023-09-13 21:15 UTC
Stained glass doesn't render
When I place pink stained glass, it's invisible

**Resourcepack in use**
Default resource pack

**System information**
The specs of your computer, example:
GPU: Nvidia RTX 3060 Ti
CPU: Intel 10400f
OS: Linux

**Screenshots**
![2023-09-13_17 13 37](https://github.com/BalintCsala/VanillaPuddingTart/assets/69647964/3bdf67a5-1581-49cd-9158-f7462a187d95)

**Comment by BalintCsala** [comment] 2023-09-13 22:12
Duplicate of #22

**Closed as completed by BalintCsala** 2023-09-13 22:12 UTC
